---
- name: Install common packages using apt
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - nginx
    - python3-pip

- name: Ensure snapd is installed
  ansible.builtin.apt:
    name: snapd
    state: present
    update_cache: yes

- name: Ensure Snap service is started and enabled
  ansible.builtin.systemd:
    name: snapd
    state: started
    enabled: yes

- name: Install AWS CLI using Snap
  community.general.snap:
    name: aws-cli
    classic: yes
    state: present

- name: Install AWS SDK for Python using apt
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - python3-boto3
    - python3-botocore

- name: Download file from s3 to ec2
  amazon.aws.s3_object:
    bucket: "test-intern-github-action"
    dest: "{{ destination }}"
    object: "{{ object }}"
    mode: get
    overwrite: true
  notify: Restart nginx