---
- name: Ensure common packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ common_packages }}"

- name: Install AWS CLI using Snap
  community.general.snap:
    name: aws-cli
    classic: yes
    state: present

- name: Download file from s3 to ec2
  amazon.aws.s3_object:
    bucket: "test-intern-github-action"
    dest: "{{ destination }}"
    object: "{{ object }}"
    mode: get
    overwrite: true
  notify: Restart nginx