---
- name: Install python3-pip and nginx
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    up-date_cache: true
  with_item:
    - nginx
    - python3-pip

- name: Ensure snapd is installed
  apt:
    name: snapd
    state: present
    update_cache: yes

- name: Ensure Snap service is started and enabled
  systemd:
    name: snapd
    state: started
    enabled: yes

- name: Install AWS CLI using Snap
  snap:
    name: aws-cli
    classic: yes
    state: present

- name: Install boto3 and botocore using apt
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_item:
    - python3-boto3
    - python3-botocore

- name: Download file from s3 to ec2
  amazon.aws.s3_object:
    bucket: "test-intern-github-action"
    dest: {{ destination }}
    object: {{ object }}
    mode: get
    overwrite: true
  notify: Restart nginx