---
- name: Install common packages using apt
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - nginx
    - python3-pip
    - snapd
    - python3-boto3
    - python3-botocore


- name: Install AWS CLI using Snap
  community.general.snap:
    name: aws-cli
    classic: yes
    state: present

- name: Download file from s3 to ec2
  amazon.aws.s3_object:
    bucket: "test-intern-github-action"
    dest: "{{ destination }}"
    object: "{{ object }}"
    mode: get
    overwrite: true
  notify: Restart nginx