---
- hosts: aws_ec2
  gather_facts: true
  become: true
  roles:
    - website
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: 8586-terraform-state 
    ansible_aws_ssm_timeout: 300
    ansible_python_interpreter: /usr/bin/python3
    